language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

services:
  - memcached
  - redis-server

env:
  - DJANGO="Django>=1.6,<1.7"
  - DJANGO="Django>=1.7,<1.8"

sudo: false

install:
  - pip install $DJANGO coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]];
    then
      pip install -r runtests_requirements_py3.txt;
    else
      pip install -r runtests_requirements_py2.txt;
    fi

before_script:
    - psql -c 'CREATE USER cachalot CREATEDB;' -U postgres
    - psql -c 'CREATE DATABASE cachalot OWNER cachalot;' -U postgres
    - mysql -u root -e 'CREATE DATABASE cachalot;'

script:
  - CACHE_BACKEND=redis     DB_ENGINE=sqlite3    coverage run -a --source=cachalot ./runtests.py
  - CACHE_BACKEND=redis     DB_ENGINE=postgresql coverage run -a --source=cachalot ./runtests.py
  - CACHE_BACKEND=redis     DB_ENGINE=mysql      coverage run -a --source=cachalot ./runtests.py
  - CACHE_BACKEND=memcached DB_ENGINE=sqlite3    coverage run -a --source=cachalot ./runtests.py
  - CACHE_BACKEND=memcached DB_ENGINE=postgresql coverage run -a --source=cachalot ./runtests.py
  - CACHE_BACKEND=memcached DB_ENGINE=mysql      coverage run -a --source=cachalot ./runtests.py
  - if [[ $DJANGO == "Django>=1.7,<1.8" ]]; then
    CACHE_BACKEND=locmem    DB_ENGINE=sqlite3    coverage run -a --source=cachalot ./runtests.py;
    CACHE_BACKEND=locmem    DB_ENGINE=postgresql coverage run -a --source=cachalot ./runtests.py;
    CACHE_BACKEND=locmem    DB_ENGINE=mysql      coverage run -a --source=cachalot ./runtests.py;
    CACHE_BACKEND=filebased DB_ENGINE=sqlite3    coverage run -a --source=cachalot ./runtests.py;
    CACHE_BACKEND=filebased DB_ENGINE=postgresql coverage run -a --source=cachalot ./runtests.py;
    CACHE_BACKEND=filebased DB_ENGINE=mysql      coverage run -a --source=cachalot ./runtests.py;
    if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then
    CACHE_BACKEND=pylibmc   DB_ENGINE=sqlite3    coverage run -a --source=cachalot ./runtests.py;
    CACHE_BACKEND=pylibmc   DB_ENGINE=postgresql coverage run -a --source=cachalot ./runtests.py;
    CACHE_BACKEND=pylibmc   DB_ENGINE=mysql      coverage run -a --source=cachalot ./runtests.py;
    fi
    fi

after_success: coveralls

matrix:
  exclude:
    - python: 2.6
      env: DJANGO="Django>=1.7,<1.8"
