language: python

services:
  - memcached
  - redis-server

install: pip install tox coveralls

before_script:
  - psql -c 'CREATE USER cachalot CREATEDB;' -U postgres
  - psql -c 'CREATE DATABASE cachalot OWNER cachalot;' -U postgres
  - mysql -u root -e 'CREATE DATABASE cachalot;'

script: tox

after_success: coveralls
