language: python

services:
  - memcached
  - redis-server

env:
    - TOXENV=py2.6-django1.6-sqlite3-{locmem,redis,memcached}
    - TOXENV=py2.6-django1.6-postgresql-{locmem,redis,memcached}
    - TOXENV=py2.6-django1.6-mysql-{locmem,redis,memcached}
    - TOXENV=py2.7-django1.6-sqlite3-{locmem,redis,memcached}
    - TOXENV=py2.7-django1.6-postgresql-{locmem,redis,memcached}
    - TOXENV=py2.7-django1.6-mysql-{locmem,redis,memcached}
    - TOXENV=py2.7-django1.7-sqlite3-{locmem,redis,memcached}
    - TOXENV=py2.7-django1.7-postgresql-{locmem,redis,memcached}
    - TOXENV=py2.7-django1.7-mysql-{locmem,redis,memcached}
    - TOXENV=py{3.2,3.3,3.4}-django1.6-sqlite3-{locmem,redis,memcached}
    - TOXENV=py{3.2,3.3,3.4}-django1.6-postgresql-{locmem,redis,memcached}
    - TOXENV=py{3.2,3.3,3.4}-django1.6-mysql-{locmem,redis,memcached}
    - TOXENV=py{3.2,3.3,3.4}-django1.7-sqlite3-{locmem,redis,memcached}
    - TOXENV=py{3.2,3.3,3.4}-django1.7-postgresql-{locmem,redis,memcached}
    - TOXENV=py{3.2,3.3,3.4}-django1.7-mysql-{locmem,redis,memcached}

install: pip install tox coveralls

before_script:
  - psql -c 'CREATE USER cachalot CREATEDB;' -U postgres
  - psql -c 'CREATE DATABASE cachalot OWNER cachalot;' -U postgres
  - mysql -u root -e 'CREATE DATABASE cachalot;'

script: tox -e $TOXENV

after_success: coveralls
